AirsoftShop/Controllers/CartController.cs
using AirsoftShop.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB;
using OnlineShop.DB.Data.Interfacees;

namespace AirsoftShop.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IProductsDbRepository _productsDbRepository;
        private readonly ICartsDbRepository _cartsDbRepository;

        public CartController(ICartsDbRepository cartsDbRepository, IProductsDbRepository productsDbRepository)
        {
            _cartsDbRepository = cartsDbRepository;
            _productsDbRepository = productsDbRepository;
        }
        public IActionResult Index()
        {
            var cart = _cartsDbRepository.TryGetByUserId(Constants.UserId);
            return View(cart.ToCartViewModel());
        }
        public IActionResult Add(Guid productId)  // +
        {
            var product = _productsDbRepository.TryGetById(productId);
            _cartsDbRepository.Add(product, Constants.UserId);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult DecreaseAmount(Guid productId) // -
        {
            var product = _productsDbRepository.TryGetById(productId);
            _cartsDbRepository.DecreaseAmount(productId, Constants.UserId);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Clear()
        {
            _cartsDbRepository.Clear(Constants.UserId);
            return RedirectToAction(nameof(Index));
        }

    }
}

AirsoftShop/Controllers/FavoriteController.cs
using AirsoftShop.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB;
using OnlineShop.DB.Data.Interfacees;

namespace AirsoftShop.Controllers
{
    [Authorize]
    public class FavoriteController : Controller
    {
        private readonly IFavoriteDbRepository _favoriteDbRepository;
        private readonly IProductsDbRepository _productsDbRepository;

        public FavoriteController(IFavoriteDbRepository favoriteDbRepository, IProductsDbRepository productsDbRepository)
        {
            _favoriteDbRepository = favoriteDbRepository;
            _productsDbRepository = productsDbRepository;
        }

        public IActionResult Index()
        {
            var products = _favoriteDbRepository.GetAll(Constants.UserId);
            return View(products.ToProductViewModels());
        }
        public IActionResult Add(Guid productId)
        {
            var product = _productsDbRepository.TryGetById(productId);
            _favoriteDbRepository.Add(Constants.UserId, product);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(Guid productId)
        {
            _favoriteDbRepository.Remove(Constants.UserId, productId);
            return RedirectToAction(nameof(Index));
        }
    }
}

AirsoftShop/Views/Favorite/Index.cshtml
@model List<ProductViewModel>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link rel="stylesheet" href="~/css/products-grid.css" />

@if (Model == null || Model.Count == 0)
{
    <div class="d-flex justify-content-center align-items-center" style="height: 70vh;">
        <div class="empty-favorites">
            <div class="heart-icon">
                <i class="far fa-heart"></i>
            </div>
            <h2>Ваш список избранного пуст</h2>
            <p>Сохраняйте понравившиеся товары в избранное, чтобы вернуться к ним позже</p>
            <a class="btn-catalog" asp-area="" asp-controller="Home" asp-action="Index">
                <i class="fas fa-arrow-left"></i>Перейти в каталог
            </a>
        </div>
    </div>
}
else
{
    <div class="products-grid-container">
        @foreach (var product in Model)
        {
            <div class="product-card">
                <div class="product-image-wrapper">
                    <img class="product-image" src="@product.ImageUrl" alt="@product.Name">
                </div>
                <div class="product-info">
                    <div class="product-title text-center">@product.Name</div>
                    <div class="product-description text-center">@product.Descriprion</div>
                    <div class="product-price text-center">@product.Cost ₽</div>
                    <div class="btn-container">
                        <a class="btn btn-cart" asp-area="" asp-controller="Cart" asp-action="Add" asp-route-productId="@product.Id" role="button">
                            <i class="fas fa-plus"></i>
                        </a>
                        <a class="btn btn-favorite" asp-area="" asp-controller="Favorite" asp-action="Remove" asp-route-productId="@product.Id" role="button">
                            <i class="fas fa-minus"></i>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
}